### ISSUE TITLE
P1 Support

### ISSUE THREAD

**Issue by sbclint** [LukeUSMC/ds18b20-photon#1]
In file included from DS18B20/DS18B20.h:1:0,
                 from measuredisplayt.cpp:5:
This looks like an error in DS18B20 library. 

DS18B20/Particle-OneWire.h:125:6: error: #error "**\* PLATFORM_ID not supported by this library. PLATFORM should be Core or Photon **_"
     #error "**_ PLATFORM_ID not supported by this library. PLATFORM should be Core or Photon ***"

I am using the SparkFun Photon RedBoard (P1).

**Comment by LFigg** [comment]
What is the Platform ID the RedBoard is giving you?  I will get it added.

**Comment by rafiki270** [comment]
I have created a pull request for another board but this might be a better solution that could solve all these board issues for good ... https://community.particle.io/t/redbear-duo-and-ds18b20-library-gives-platform-error/20463/8?u=rafiki270

**Comment by LFigg** [comment]
merged.
